name: WServer

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 999999999999

    steps:
    - name: Download Nginx.
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/elmodunk/Leebatch/main/partone.bat -OutFile partone.bat
        Invoke-WebRequest https://raw.githubusercontent.com/elmodunk/Leebatch/main/surf-ace.png -OutFile wallpaper.png
        Invoke-WebRequest https://raw.githubusercontent.com/elmodunk/Leebatch/main/parttwo.bat -OutFile parttwo.bat
        Invoke-WebRequest https://raw.githubusercontent.com/elmodunk/Leebatch/main/partthree.bat -OutFile partthree.bat
    - name: Extract Nginx.
      run: Expand-Archive ngrok.zip
    - name: Connect Nginx.
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Action.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy wallpaper.png D:\a\wallpaper.png
        copy parttwo.bat D:\a\parttwo.bat
    - name: Making TAP
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
    - name: Connect.
      run: cmd /c partone.bat
    - name: Successful implementation!
      run: cmd /c partthree.bat
